Update all the requirements
CERT-Polska/mquery pull request #246
Opened 2021-12-07 02:27 UTC by msm-code

**Your checklist for this pull request**
- [x] I've read the [contributing guideline](https://github.com/CERT-Polska/mquery/blob/master/CONTRIBUTING.md).
- [x] I've tested my changes by building and running mquery, and testing changed functionality (if applicable)
- [ ] I've added automated tests for my change (if applicable, optional)
- [ ] I've updated documentation to reflect my change (if applicable)

**What is the current behaviour?**
Dependencies are updated

**What is the new behaviour?**
Suprisingly, everything seems to work after updating the dependenceis (and minor fixes). I'll do more testing later, but I think tihs is ready for review.

**Test plan**
Click around

**Closing issues**

fixes #231 (tested)
fixes #235

2021-12-07 10:22 UTC, nazywam commented on src/app.py
> +        raise Response("No such file in result set.", status_code=404)
```suggestion
        return Response("No such file in result set.", status_code=404)
```
probably?

2021-12-07 10:25 UTC, nazywam requested changes
Looks good, the other failed tests seem unrelated.

What's the usecase of `requirements.plain.txt`, should we maybe put it in a comment somewhere?

2021-12-07 20:18 UTC, msm-code commented
Uh oh, thanks for catching this. I've actually fixed this and forgot to commit :facepalm:.

I'll apply the changes and do some more testing.

2021-12-07 20:22 UTC, msm-code commented
> What's the usecase of requirements.plain.txt, should we maybe put it in a comment somewhere?

The idea was that I had to do some guesswork to find "original" dependencies. As you can see we had some "old" dependencies that were removed (for example, werkzeug), but stayed in the requirements because they were a transitive dependency of some project.

Basically the difference between packages.json and packeges.lock or something. I don't know a good place for a file like this - any ideas?

2021-12-07 20:33 UTC, msm-code commented
Actually this also fixes #100 - added to the description.

2021-12-08 00:39 UTC, nazywam approved these changes

2021-12-08 01:00 UTC, merged