Draft: fix: rewrite query_ursadb not to use iterators
CERT-Polska/mquery pull request #420
Opened 2024-10-09 13:32 UTC by mickol34

**Your checklist for this pull request**
- [ ] I've read the [contributing guideline](https://github.com/CERT-Polska/mquery/blob/master/CONTRIBUTING.md).
- [ ] I've tested my changes by building and running mquery, and testing changed functionality (if applicable)
- [ ] I've added automated tests for my change (if applicable, optional)
- [ ] I've updated documentation to reflect my change (if applicable)

**What is the current behaviour?**

TODO: fill after changing from draft

**What is the new behaviour?**

**Test plan**

**Closing issues**

fixes #issuenumber

2024-10-09 14:01 UTC, msm-cert commented on src/tasks.py
> +                update(QueryResult).where(QueryResult.job_id == result.job_id).values(files=result.files[batch_size+1:])
Doesn't look safe with regard to parallelism/multithreading.

2024-10-09 14:01 UTC, msm-cert commented on src/tasks.py
> +                update(QueryResult).where(QueryResult.job_id == result.job_id).values(files=result.files[batch_size+1:])
Also you're missing one file every time (should be `[batch_size:]` probably).

2024-10-10 08:46 UTC, mickol34 commented on src/models/queryresult.py
> +  files: List[str] = Field(sa_column=Column(ARRAY(String)))
So this means I should multiple objects for every file returned from ```.query()```?

2024-10-16 16:11 UTC, msm-cert commented
BTW. this fails because QueryResult table does not exist in the DB. You need to create alembic migration for it (see also recent PR about enum rework). I didn't re-review the rest of the code yet.

2024-10-17 13:55 UTC, mickol34 commented
Referring to #381 I'm not sure if ```ursadb.pop()``` is dead code, if it's used in ```all_indexed_files``` and ```all_indexed_names``` functions. If there are any other cleanups and/or tests to add, please comment below for me to fix them.

2024-10-31 03:01 UTC, msm-cert requested changes
Ok, I think we can continue with this but with some large changes:

1. Restore query to the previous version (so return an iterator)
2. When querying, use that iterator to immediately add all the files from the result to the database (call `pop` in a loop and insert to the database, no need to handle `was_locked` state)
3. I think QueryResult should be something like `JobFile (id: int, job_id: int, file: str)`, so workers don't have to get all the results at once (can just select with limit and offset)
3. Alternatively, insert multiple QueryResults into the database, each with a batch of files (this is easier to implement but is less flexible. But still OK probably)
4. Importantly, when adding tasks: `agent.queue.enqueue(...` don't add filenames there. That's because it's stored in redis (== ram) and can potentially be very large. Instead, store just offset or batch_id (depending on which option in the previous you picked)

The reasoning here is that we prefer to have files in the database instead of in the opaque and weird ursadb iterator, but we have to be careful to avoid keeping the entire set of files at once in memory. In most cases this set will be small, but we can't OOM if someone does a huge query (this was actually a problem in the past).

I realise this may sound a bit convoluted, feel free to contact me in case of any questions

2025-03-20 17:41 UTC, msm-cert commented
Hi!

I'm closing it because since we didn't decide to merge it for 4 months it probably won't be merged any time soon.

But I still think it's a good idea, so maybe in the future we'll reuse this PR.

2025-03-20 17:41 UTC, closed without merging