395 add the information about match context to the database
CERT-Polska/mquery pull request #439
Opened 2024-11-22 09:04 UTC by michalkrzem

**Your checklist for this pull request**
- [ ] I've read the [contributing guideline](https://github.com/CERT-Polska/mquery/blob/master/CONTRIBUTING.md).
- [ ] I've tested my changes by building and running mquery, and testing changed functionality (if applicable)
- [ ] I've added automated tests for my change (if applicable, optional)
- [ ] I've updated documentation to reflect my change (if applicable)

**What is the current behaviour?**

**What is the new behaviour?**

**Test plan**

**Closing issues**

fixes #issuenumber

2024-12-12 12:03 UTC, msm-cert commented on src/tasks.py
> +                expression_keys = []
Since this is only used for presence checking, this should be a set instead of a list. But I think it's not necessary at all (see next comment)

2024-12-12 12:10 UTC, msm-cert commented on src/tasks.py
> +                    context.update({str(yara_match): match_context})
Finally, this expression is overly complicated - I believe
```
context.update({A: B})
```
is equivalent to
```
context[A] = B
```

2024-12-13 13:01 UTC, michalkrzem commented on src/tasks.py
> +                        orig_name=orig_name,
I read somewhere that when we use such a notation, we don’t have to worry about the order of the arguments, and we already know during the function call what variables are being assigned to (if the naming differs). That was someone’s opinion; I’ll adapt to the project then. :)

2024-12-13 13:03 UTC, michalkrzem commented on src/tasks.py
> +                    context.update({str(yara_match): match_context})
Here, in the match key, we have information about the string we are searching for. But okay, I’ll replace the list with a dictionry.

2024-12-19 12:17 UTC, msm-cert approved these changes
Thanks! Looks good. Sorry for waiting

2024-12-19 12:17 UTC, msm-cert commented on src/tasks.py
> +                (before, matching, after,) = read_bytes_with_context(
nitpick
```suggestion
                (before, matching, after,) = read_bytes_with_context(
```

2024-12-19 12:17 UTC, msm-cert commented on src/tasks.py
> +    ]
nitpick, but we save 2 LoC - only negative numbers are a problem so this works too
```suggestion
    before = data[max(0, offset - byte_range) : offset]
    matching = data[offset : offset + matched_length]
    after = data[offset + matched_length : offset + matched_length + byte_range]
```

2024-12-19 12:24 UTC, msm-cert requested changes

2024-12-19 12:24 UTC, msm-cert commented on src/tasks.py
> +                match_context[expression_key] = {
I'll fix the style in a second but... `expression_key` is an object. So match_context is not a `Dict[str, ...]`, so context is not `Dict[..., Dict[str, ...]]`, so something's wrong

2024-12-19 13:04 UTC, msm-cert approved these changes

2024-12-19 13:04 UTC, merged